apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: day01-node-ingress
  namespace: stagging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - day01.local
    secretName: day01-tls
  rules:
  - host: day01.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: day01-node-service
            port:
              number: 80