apiVersion: v1
kind: Service
metadata:
  name: day01-node-service
  namespace: stagging
  labels:
    app: day01-node-app
spec:
  selector:
    app: day01-node-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP